// #undef RGBLIGHT_ANIMATIONS
// #undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #undef RGBLIGHT_EFFECT_SNAKE
// #undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE

#undef VENDOR_ID
#define VENDOR_ID 0x1234

#undef PRODUCT_ID
#define PRODUCT_ID 0x5678

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61