name: Build QMK firmware
on: [push]
jobs:
  find-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - id: set-targets
        run: echo "targets=$(ls keyboards | jq -R '[.]' | jq -s -c 'add')" >> $GITHUB_OUTPUT
  build:
    needs: find-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        KBD: ${{ fromJson(needs.find-targets.outputs.targets) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Build firmware
        run: nix build --out-link result-${{ matrix.KBD }} .#${{ matrix.KBD }}
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.KBD }}
          path: result-${{ matrix.KBD }}/bin/*
